-- Auto-generated by gen_memory_pkg.py
-- Source instr HEX: add.inst_rom.hex
-- Source data  HEX: add.data_rom.hex
-- Do not edit by hand.

library ieee;
use ieee.std_logic_1164.all;

package memory_pkg is

  -----------------------------------------------------------------------------
  -- Instruction memory
  -----------------------------------------------------------------------------
  constant INST_ROM_BASE_ADDRESS          : integer := 16#00000000#;
  constant INSTRUCTION_MEMORY_SIZE_BYTES  : integer := 1540;
  constant INSTRUCTION_MEMORY_SIZE_WORDS  : integer := INSTRUCTION_MEMORY_SIZE_BYTES / 4;

  type INSTRUCTION_MEMORY_ARRAY_t is array (0 to INSTRUCTION_MEMORY_SIZE_WORDS-1)
    of std_logic_vector(31 downto 0);

  constant INSTRUCTION_MEMORY_CONTENT : INSTRUCTION_MEMORY_ARRAY_t := (
    x"00000093",  -- word 0
    x"00000113",  -- word 1
    x"00000193",  -- word 2
    x"00000213",  -- word 3
    x"00000293",  -- word 4
    x"00000313",  -- word 5
    x"00000393",  -- word 6
    x"00000413",  -- word 7
    x"00000493",  -- word 8
    x"00000513",  -- word 9
    x"00000593",  -- word 10
    x"00000613",  -- word 11
    x"00000693",  -- word 12
    x"00000713",  -- word 13
    x"00000793",  -- word 14
    x"00000813",  -- word 15
    x"00000893",  -- word 16
    x"00000913",  -- word 17
    x"00000993",  -- word 18
    x"00000A13",  -- word 19
    x"00000A93",  -- word 20
    x"00000B13",  -- word 21
    x"00000B93",  -- word 22
    x"00000C13",  -- word 23
    x"00000C93",  -- word 24
    x"00000D13",  -- word 25
    x"00000D93",  -- word 26
    x"00000E13",  -- word 27
    x"00000E93",  -- word 28
    x"00000F13",  -- word 29
    x"00000F93",  -- word 30
    x"01000297",  -- word 31
    x"F8428293",  -- word 32
    x"02000317",  -- word 33
    x"F7C30313",  -- word 34
    x"02000397",  -- word 35
    x"F7438393",  -- word 36
    x"00730C63",  -- word 37
    x"0002AE03",  -- word 38
    x"01C32023",  -- word 39
    x"00428293",  -- word 40
    x"00430313",  -- word 41
    x"FEDFF06F",  -- word 42
    x"02000297",  -- word 43
    x"F5428293",  -- word 44
    x"02000317",  -- word 45
    x"F4C30313",  -- word 46
    x"00000393",  -- word 47
    x"00628863",  -- word 48
    x"0072A023",  -- word 49
    x"00428293",  -- word 50
    x"FF5FF06F",  -- word 51
    x"00200193",  -- word 52
    x"00000593",  -- word 53
    x"00000613",  -- word 54
    x"00C58733",  -- word 55
    x"00000393",  -- word 56
    x"4C771663",  -- word 57
    x"00300193",  -- word 58
    x"00100593",  -- word 59
    x"00100613",  -- word 60
    x"00C58733",  -- word 61
    x"00200393",  -- word 62
    x"4A771A63",  -- word 63
    x"00400193",  -- word 64
    x"00300593",  -- word 65
    x"00700613",  -- word 66
    x"00C58733",  -- word 67
    x"00A00393",  -- word 68
    x"48771E63",  -- word 69
    x"00500193",  -- word 70
    x"00000593",  -- word 71
    x"FFFF8637",  -- word 72
    x"00C58733",  -- word 73
    x"FFFF83B7",  -- word 74
    x"48771263",  -- word 75
    x"00600193",  -- word 76
    x"800005B7",  -- word 77
    x"00000613",  -- word 78
    x"00C58733",  -- word 79
    x"800003B7",  -- word 80
    x"46771663",  -- word 81
    x"00700193",  -- word 82
    x"800005B7",  -- word 83
    x"FFFF8637",  -- word 84
    x"00C58733",  -- word 85
    x"7FFF83B7",  -- word 86
    x"44771A63",  -- word 87
    x"00800193",  -- word 88
    x"00000593",  -- word 89
    x"00008637",  -- word 90
    x"FFF60613",  -- word 91
    x"00C58733",  -- word 92
    x"000083B7",  -- word 93
    x"FFF38393",  -- word 94
    x"42771A63",  -- word 95
    x"00900193",  -- word 96
    x"800005B7",  -- word 97
    x"FFF58593",  -- word 98
    x"00000613",  -- word 99
    x"00C58733",  -- word 100
    x"800003B7",  -- word 101
    x"FFF38393",  -- word 102
    x"40771A63",  -- word 103
    x"00A00193",  -- word 104
    x"800005B7",  -- word 105
    x"FFF58593",  -- word 106
    x"00008637",  -- word 107
    x"FFF60613",  -- word 108
    x"00C58733",  -- word 109
    x"800083B7",  -- word 110
    x"FFE38393",  -- word 111
    x"3E771863",  -- word 112
    x"00B00193",  -- word 113
    x"800005B7",  -- word 114
    x"00008637",  -- word 115
    x"FFF60613",  -- word 116
    x"00C58733",  -- word 117
    x"800083B7",  -- word 118
    x"FFF38393",  -- word 119
    x"3C771863",  -- word 120
    x"00C00193",  -- word 121
    x"800005B7",  -- word 122
    x"FFF58593",  -- word 123
    x"FFFF8637",  -- word 124
    x"00C58733",  -- word 125
    x"7FFF83B7",  -- word 126
    x"FFF38393",  -- word 127
    x"3A771863",  -- word 128
    x"00D00193",  -- word 129
    x"00000593",  -- word 130
    x"FFF00613",  -- word 131
    x"00C58733",  -- word 132
    x"FFF00393",  -- word 133
    x"38771C63",  -- word 134
    x"00E00193",  -- word 135
    x"FFF00593",  -- word 136
    x"00100613",  -- word 137
    x"00C58733",  -- word 138
    x"00000393",  -- word 139
    x"38771063",  -- word 140
    x"00F00193",  -- word 141
    x"FFF00593",  -- word 142
    x"FFF00613",  -- word 143
    x"00C58733",  -- word 144
    x"FFE00393",  -- word 145
    x"36771463",  -- word 146
    x"01000193",  -- word 147
    x"00100593",  -- word 148
    x"80000637",  -- word 149
    x"FFF60613",  -- word 150
    x"00C58733",  -- word 151
    x"800003B7",  -- word 152
    x"34771663",  -- word 153
    x"01100193",  -- word 154
    x"00D00593",  -- word 155
    x"00B00613",  -- word 156
    x"00C585B3",  -- word 157
    x"01800393",  -- word 158
    x"32759A63",  -- word 159
    x"01200193",  -- word 160
    x"00E00593",  -- word 161
    x"00B00613",  -- word 162
    x"00C58633",  -- word 163
    x"01900393",  -- word 164
    x"30761E63",  -- word 165
    x"01300193",  -- word 166
    x"00D00593",  -- word 167
    x"00B585B3",  -- word 168
    x"01A00393",  -- word 169
    x"30759463",  -- word 170
    x"01400193",  -- word 171
    x"00000213",  -- word 172
    x"00D00093",  -- word 173
    x"00B00113",  -- word 174
    x"00208733",  -- word 175
    x"00070313",  -- word 176
    x"00120213",  -- word 177
    x"00200293",  -- word 178
    x"FE5214E3",  -- word 179
    x"01800393",  -- word 180
    x"2C731E63",  -- word 181
    x"01500193",  -- word 182
    x"00000213",  -- word 183
    x"00E00093",  -- word 184
    x"00B00113",  -- word 185
    x"00208733",  -- word 186
    x"00000013",  -- word 187
    x"00070313",  -- word 188
    x"00120213",  -- word 189
    x"00200293",  -- word 190
    x"FE5212E3",  -- word 191
    x"01900393",  -- word 192
    x"2A731663",  -- word 193
    x"01600193",  -- word 194
    x"00000213",  -- word 195
    x"00F00093",  -- word 196
    x"00B00113",  -- word 197
    x"00208733",  -- word 198
    x"00000013",  -- word 199
    x"00000013",  -- word 200
    x"00070313",  -- word 201
    x"00120213",  -- word 202
    x"00200293",  -- word 203
    x"FE5210E3",  -- word 204
    x"01A00393",  -- word 205
    x"26731C63",  -- word 206
    x"01700193",  -- word 207
    x"00000213",  -- word 208
    x"00D00093",  -- word 209
    x"00B00113",  -- word 210
    x"00208733",  -- word 211
    x"00120213",  -- word 212
    x"00200293",  -- word 213
    x"FE5216E3",  -- word 214
    x"01800393",  -- word 215
    x"24771863",  -- word 216
    x"01800193",  -- word 217
    x"00000213",  -- word 218
    x"00E00093",  -- word 219
    x"00B00113",  -- word 220
    x"00000013",  -- word 221
    x"00208733",  -- word 222
    x"00120213",  -- word 223
    x"00200293",  -- word 224
    x"FE5214E3",  -- word 225
    x"01900393",  -- word 226
    x"22771263",  -- word 227
    x"01900193",  -- word 228
    x"00000213",  -- word 229
    x"00F00093",  -- word 230
    x"00B00113",  -- word 231
    x"00000013",  -- word 232
    x"00000013",  -- word 233
    x"00208733",  -- word 234
    x"00120213",  -- word 235
    x"00200293",  -- word 236
    x"FE5212E3",  -- word 237
    x"01A00393",  -- word 238
    x"1E771A63",  -- word 239
    x"01A00193",  -- word 240
    x"00000213",  -- word 241
    x"00D00093",  -- word 242
    x"00000013",  -- word 243
    x"00B00113",  -- word 244
    x"00208733",  -- word 245
    x"00120213",  -- word 246
    x"00200293",  -- word 247
    x"FE5214E3",  -- word 248
    x"01800393",  -- word 249
    x"1C771463",  -- word 250
    x"01B00193",  -- word 251
    x"00000213",  -- word 252
    x"00E00093",  -- word 253
    x"00000013",  -- word 254
    x"00B00113",  -- word 255
    x"00000013",  -- word 256
    x"00208733",  -- word 257
    x"00120213",  -- word 258
    x"00200293",  -- word 259
    x"FE5212E3",  -- word 260
    x"01900393",  -- word 261
    x"18771C63",  -- word 262
    x"01C00193",  -- word 263
    x"00000213",  -- word 264
    x"00F00093",  -- word 265
    x"00000013",  -- word 266
    x"00000013",  -- word 267
    x"00B00113",  -- word 268
    x"00208733",  -- word 269
    x"00120213",  -- word 270
    x"00200293",  -- word 271
    x"FE5212E3",  -- word 272
    x"01A00393",  -- word 273
    x"16771463",  -- word 274
    x"01D00193",  -- word 275
    x"00000213",  -- word 276
    x"00B00113",  -- word 277
    x"00D00093",  -- word 278
    x"00208733",  -- word 279
    x"00120213",  -- word 280
    x"00200293",  -- word 281
    x"FE5216E3",  -- word 282
    x"01800393",  -- word 283
    x"14771063",  -- word 284
    x"01E00193",  -- word 285
    x"00000213",  -- word 286
    x"00B00113",  -- word 287
    x"00E00093",  -- word 288
    x"00000013",  -- word 289
    x"00208733",  -- word 290
    x"00120213",  -- word 291
    x"00200293",  -- word 292
    x"FE5214E3",  -- word 293
    x"01900393",  -- word 294
    x"10771A63",  -- word 295
    x"01F00193",  -- word 296
    x"00000213",  -- word 297
    x"00B00113",  -- word 298
    x"00F00093",  -- word 299
    x"00000013",  -- word 300
    x"00000013",  -- word 301
    x"00208733",  -- word 302
    x"00120213",  -- word 303
    x"00200293",  -- word 304
    x"FE5212E3",  -- word 305
    x"01A00393",  -- word 306
    x"0E771263",  -- word 307
    x"02000193",  -- word 308
    x"00000213",  -- word 309
    x"00B00113",  -- word 310
    x"00000013",  -- word 311
    x"00D00093",  -- word 312
    x"00208733",  -- word 313
    x"00120213",  -- word 314
    x"00200293",  -- word 315
    x"FE5214E3",  -- word 316
    x"01800393",  -- word 317
    x"0A771C63",  -- word 318
    x"02100193",  -- word 319
    x"00000213",  -- word 320
    x"00B00113",  -- word 321
    x"00000013",  -- word 322
    x"00E00093",  -- word 323
    x"00000013",  -- word 324
    x"00208733",  -- word 325
    x"00120213",  -- word 326
    x"00200293",  -- word 327
    x"FE5212E3",  -- word 328
    x"01900393",  -- word 329
    x"08771463",  -- word 330
    x"02200193",  -- word 331
    x"00000213",  -- word 332
    x"00B00113",  -- word 333
    x"00000013",  -- word 334
    x"00000013",  -- word 335
    x"00F00093",  -- word 336
    x"00208733",  -- word 337
    x"00120213",  -- word 338
    x"00200293",  -- word 339
    x"FE5212E3",  -- word 340
    x"01A00393",  -- word 341
    x"04771C63",  -- word 342
    x"02300193",  -- word 343
    x"00F00093",  -- word 344
    x"00100133",  -- word 345
    x"00F00393",  -- word 346
    x"04711263",  -- word 347
    x"02400193",  -- word 348
    x"02000093",  -- word 349
    x"00008133",  -- word 350
    x"02000393",  -- word 351
    x"02711863",  -- word 352
    x"02500193",  -- word 353
    x"000000B3",  -- word 354
    x"00000393",  -- word 355
    x"02709063",  -- word 356
    x"02600193",  -- word 357
    x"01000093",  -- word 358
    x"01E00113",  -- word 359
    x"00208033",  -- word 360
    x"00000393",  -- word 361
    x"00701463",  -- word 362
    x"00301E63",  -- word 363
    x"00018063",  -- word 364
    x"00018593",  -- word 365
    x"10200513",  -- word 366
    x"01F01013",  -- word 367
    x"00100073",  -- word 368
    x"40705013",  -- word 369
    x"00100193",  -- word 370
    x"10100513",  -- word 371
    x"01F01013",  -- word 372
    x"00100073",  -- word 373
    x"40705013",  -- word 374
    x"00100073",  -- word 375
    x"00000000",  -- word 376
    x"00000000",  -- word 377
    x"00000000",  -- word 378
    x"00000000",  -- word 379
    x"00000000",  -- word 380
    x"00000000",  -- word 381
    x"00000000",  -- word 382
    x"00000000",  -- word 383
    x"00000000"  -- word 384
  );

  -----------------------------------------------------------------------------
  -- Data RAM
  -----------------------------------------------------------------------------
  constant DATA_RAM_BASE_ADDRESS        : integer := 16#02000000#;
  constant DATA_RAM_MEMORY_SIZE_BYTES   : integer := 4096;
  constant DATA_RAM_MEMORY_SIZE_WORDS   : integer := DATA_RAM_MEMORY_SIZE_BYTES / 4;

  type DATA_RAM_MEMORY_ARRAY_t is array (0 to DATA_RAM_MEMORY_SIZE_WORDS-1)
    of std_logic_vector(31 downto 0);

  -----------------------------------------------------------------------------
  -- Data ROM
  -----------------------------------------------------------------------------
  constant DATA_ROM_BASE_ADDRESS        : integer := 16#01000000#;
  constant DATA_ROM_MEMORY_SIZE_BYTES   : integer := 8;
  constant DATA_ROM_MEMORY_SIZE_WORDS   : integer := DATA_ROM_MEMORY_SIZE_BYTES / 4;

  type DATA_ROM_MEMORY_ARRAY_t is array (0 to DATA_ROM_MEMORY_SIZE_WORDS-1)
    of std_logic_vector(31 downto 0);

  constant DATA_ROM_MEMORY_CONTENT : DATA_ROM_MEMORY_ARRAY_t := (
    x"00000000",  -- word 0
    x"00000000"  -- word 1
  );

end package memory_pkg;

package body memory_pkg is
end package body memory_pkg;
