-- Auto-generated by gen_memory_pkg.py
-- Source instr HEX: inst_rom.hex
-- Source data  HEX: data_rom.hex
-- Do not edit by hand.

library ieee;
use ieee.std_logic_1164.all;

package memory_pkg is

  -----------------------------------------------------------------------------
  -- Instruction memory
  -----------------------------------------------------------------------------
  constant INST_ROM_BASE_ADDRESS          : integer := 16#00000000#;
  constant INSTRUCTION_MEMORY_SIZE_BYTES  : integer := 280;
  constant INSTRUCTION_MEMORY_SIZE_WORDS  : integer := INSTRUCTION_MEMORY_SIZE_BYTES / 4;

  type INSTRUCTION_MEMORY_ARRAY_t is array (0 to INSTRUCTION_MEMORY_SIZE_WORDS-1)
    of std_logic_vector(31 downto 0);

  constant INSTRUCTION_MEMORY_CONTENT : INSTRUCTION_MEMORY_ARRAY_t := (
    x"04000EB7",  -- word 0
    x"00100F13",  -- word 1
    x"01EEA023",  -- word 2
    x"02000117",  -- word 3
    x"05410113",  -- word 4
    x"00300F13",  -- word 5
    x"01EEA023",  -- word 6
    x"01000297",  -- word 7
    x"FF028293",  -- word 8
    x"02000317",  -- word 9
    x"FDC30313",  -- word 10
    x"02000397",  -- word 11
    x"FD438393",  -- word 12
    x"00730C63",  -- word 13
    x"0002AE03",  -- word 14
    x"01C32023",  -- word 15
    x"00428293",  -- word 16
    x"00430313",  -- word 17
    x"FEDFF06F",  -- word 18
    x"00700F13",  -- word 19
    x"01EEA023",  -- word 20
    x"02000317",  -- word 21
    x"FAC30313",  -- word 22
    x"02000397",  -- word 23
    x"FA438393",  -- word 24
    x"00000E13",  -- word 25
    x"00730863",  -- word 26
    x"01C32023",  -- word 27
    x"00430313",  -- word 28
    x"FF5FF06F",  -- word 29
    x"00F00F13",  -- word 30
    x"01EEA023",  -- word 31
    x"01F00F13",  -- word 32
    x"01EEA023",  -- word 33
    x"078000EF",  -- word 34
    x"07F00F13",  -- word 35
    x"01EEA023",  -- word 36
    x"0000006F",  -- word 37
    x"00A00793",  -- word 38
    x"00F50863",  -- word 39
    x"030007B7",  -- word 40
    x"00A7A423",  -- word 41
    x"00008067",  -- word 42
    x"030007B7",  -- word 43
    x"00D00713",  -- word 44
    x"00E7A423",  -- word 45
    x"030007B7",  -- word 46
    x"00A7A423",  -- word 47
    x"00008067",  -- word 48
    x"08050613",  -- word 49
    x"00A00693",  -- word 50
    x"03000737",  -- word 51
    x"00D00593",  -- word 52
    x"00C0006F",  -- word 53
    x"00F72423",  -- word 54
    x"02A60063",  -- word 55
    x"00054783",  -- word 56
    x"00150513",  -- word 57
    x"00078A63",  -- word 58
    x"FED796E3",  -- word 59
    x"00B72423",  -- word 60
    x"00F72423",  -- word 61
    x"FEA614E3",  -- word 62
    x"00008067",  -- word 63
    x"030007B7",  -- word 64
    x"20800713",  -- word 65
    x"01000537",  -- word 66
    x"00E7A223",  -- word 67
    x"00050513",  -- word 68
    x"FB1FF06F"  -- word 69
  );

  -----------------------------------------------------------------------------
  -- Data RAM
  -----------------------------------------------------------------------------
  constant DATA_RAM_BASE_ADDRESS        : integer := 16#02000000#;
  constant DATA_RAM_MEMORY_SIZE_BYTES   : integer := 96;
  constant DATA_RAM_MEMORY_SIZE_WORDS   : integer := DATA_RAM_MEMORY_SIZE_BYTES / 4;

  type DATA_RAM_MEMORY_ARRAY_t is array (0 to DATA_RAM_MEMORY_SIZE_WORDS-1)
    of std_logic_vector(31 downto 0);

  -----------------------------------------------------------------------------
  -- Data ROM
  -----------------------------------------------------------------------------
  constant DATA_ROM_BASE_ADDRESS        : integer := 16#01000000#;
  constant DATA_ROM_MEMORY_SIZE_BYTES   : integer := 12;
  constant DATA_ROM_MEMORY_SIZE_WORDS   : integer := DATA_ROM_MEMORY_SIZE_BYTES / 4;

  type DATA_ROM_MEMORY_ARRAY_t is array (0 to DATA_ROM_MEMORY_SIZE_WORDS-1)
    of std_logic_vector(31 downto 0);

  constant DATA_ROM_MEMORY_CONTENT : DATA_ROM_MEMORY_ARRAY_t := (
    x"746F6F42",  -- word 0
    x"2E676E69",  -- word 1
    x"0000002E"  -- word 2
  );

end package memory_pkg;

package body memory_pkg is
end package body memory_pkg;
